# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 2

version: {build}
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

notifications:
- provider: Email
  to:
  - jedmao@outlook.com
  subject: 'AppVeyor Build Failed: postcss-center'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
- provider: Email
  to:
  - jedmao@outlook.com
  subject: 'AppVeyor Build Status Changed: postcss-center'
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
